# Generated by Django 5.1.4 on 2025-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='Categoria sem uma descrição', null=True, verbose_name='Descrição'),
        ),
    ]
